### ISSUE TITLE
unable to install nilmtk and obtain redd.h5

### ISSUE THREAD

**Issue by charlicruz** [josemao/nilmtk_practicas#1]
Dear Jose,
I am trying to use files from your practicas but I can not install correctly nilmtk. I can no use it under python 3.7. Do you know how to install nilmtk in Anaconda under latest versions of matplotlib, python 3.7?Could you please provide the red.h5 file?
Thank you in advance

**Comment by josemao** [comment]
Dear Carlos, 

Thank you for your email. 

Unfortunately, I cannot help you much with the NILMTK project as I am not involved in it. I suggest contacting one of the core team in http://nilmtk.github.io/. They are all very nice and will be happy to assist you. 

Regarding the red.h5 file, I do not have it anymore. I´m sorry. Perhaps you want also ask the team to send you a copy of the file?

Best,

**Comment by charlicruz** [comment]
thank you for your response, just a quick question. Do you know how could be possible to plot one appliance from two buildings into the same graph? thanks

**Comment by josemao** [comment]
I'm not sure if I understand the question. If it is about how to load the data using NILMTK (loading the time-series data from an appliance in different buildings) then I'm afraid I cannot help. I have been detached from the NILMTK  for a long time and I do not remember the process. If it is about the actual plot, Matploblib library offers that option and there are many examples you can use in the website: 
https://matplotlib.org/gallery/index.html

I hope this helps.
